# Generated by Django 4.2.11 on 2024-05-13 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroContabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('valor', models.FloatField()),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tabla.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
                ('creacion_registro', models.DateField()),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabla.vehiculo', unique=True)),
            ],
        ),
    ]
